name: nyumets_processing
channels:
  - defaults
dependencies:
  - python=3.8
  - nipype
  - ipykernel
  - pydicom=2.2.0
  - nibabel=3.2.1
  - scipy
  - pip:
    - antspyx==0.2.9
    - dcmrtstruct2nii==1.0.19
    - pyyaml==5.4.1
    - scikit-image==0.18.2
    - rt_utils
    - dicompylercore
    - dicom_numpy
